{
 "title": "LSM Store",
 "tags": [ "Weaviate" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "LSM Strategy Replace by Level (Object Storage)",
   "type": "stat",
   "description": "Replace is used primarly for object storage, but also for inverted index hash buckets.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (level, unit) (lsm_segment_size{strategy=\"replace\"})",
     "legendFormat": "Level {{level}} / {{unit}} "
    }
   ]
  },
  {
   "title": "LSM Strategy SetCollection by Level (Inverted without frequency)",
   "type": "stat",
   "description": "SetCollections are used in the inverted index for anything that does not have a frequency, e.g. numbers, bools, etc.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (level, unit) (lsm_segment_size{strategy=\"setcollection\"})",
     "legendFormat": "Level {{level}} / {{unit}} "
    }
   ]
  },
  {
   "title": "LSM Strategy MapCollection by Level (Inverted with frequency)",
   "type": "stat",
   "description": "MapCollections are used in the inverted index for anything that has a frequency, which is mainly text and string props. Those need a frequency for BM25 calculations.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (level, unit) (lsm_segment_size{strategy=\"mapcollection\"})",
     "legendFormat": "Level {{level}} / {{unit}} "
    }
   ]
  },
  {
   "title": "Bloom Filter Hits and Misses Duration",
   "type": "timeseries",
   "description": "The bloom filters are designed to quickly produce true negatives, but sometimes they have false positive which require an actual disk lookup.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(lsm_bloom_filters_duration_ms_sum{strategy=\"replace\"}[5s])/rate(lsm_bloom_filters_duration_ms_count{strategy=\"replace\"}[5s])",
     "legendFormat": "{{operation}} ({{class_name}}/{{shard_name}})"
    }
   ]
  },
  {
   "title": "Bloom Filter False Positive Ratio",
   "type": "gauge",
   "description": "Ratio of false-positive to all requests to the bloom filter, i.e. those that required an unnecessary disk lookup.",
   "gridPos": { "h": 8, "w": 3, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(lsm_bloom_filters_duration_ms_count{operation=\"get_false_positive\"})/(sum(lsm_bloom_filters_duration_ms_count{operation=\"get_true_negative\"})+sum(lsm_bloom_filters_duration_ms_count{operation=\"get_true_positive\"})+sum(lsm_bloom_filters_duration_ms_count{operation=\"get_false_positive\"}))"
    }
   ]
  },
  {
   "title": "Bloom Filter Access",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(lsm_bloom_filters_duration_ms_count{operation=\"get_true_positive\"})",
     "legendFormat": "True Positives"
    },
    {
     "expr": "sum(lsm_bloom_filters_duration_ms_count{operation=\"get_true_negative\"})",
     "legendFormat": "True Negatives"
    },
    {
     "expr": "sum(lsm_bloom_filters_duration_ms_count{operation=\"get_false_positive\"})",
     "legendFormat": "False Positives"
    }
   ]
  },
  {
   "title": "Estimated Sizes LSM stores",
   "type": "bargauge",
   "description": "The grouping is done by strategy which means the reported Object storage value is slightly too high, as all inverted index hash buckets are also of type replace.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(lsm_segment_size{strategy=\"replace\"})",
     "legendFormat": "Object Storage"
    },
    {
     "expr": "sum(lsm_segment_size{strategy=\"mapcollection\"}) + ignoring(strategy) sum(lsm_segment_size{strategy=\"setcollection\"})",
     "legendFormat": "Inverted Index"
    }
   ]
  }
 ]
}