{
 "title": "Startup times",
 "tags": [ "Weaviate" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Startup durations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(startup_durations_ms_sum[$__interval])/rate(startup_durations_ms_count[$__interval])",
     "legendFormat": "{{operation}} ({{class_name}} / {{shard_name}})"
    }
   ]
  },
  {
   "title": "Startup all LSM buckets",
   "type": "stat",
   "description": "These times do not represent wall time. Some init processes are running in parallel, so this is CPU time. For a wall clock measurement look at total shard startup time.",
   "gridPos": { "h": 9, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(startup_durations_ms_sum{operation=\"lsm_startup_bucket\"})"
    }
   ]
  },
  {
   "title": "Startup all HNSW indexes",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(startup_durations_ms_sum{operation=\"hnsw_read_all_commitlogs\"})"
    }
   ]
  },
  {
   "title": "Total shard Startup",
   "type": "stat",
   "description": "This represents the total wall time per shard.",
   "gridPos": { "h": 9, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "startup_durations_ms_sum{operation=\"shard_total_init\"}",
     "legendFormat": "{{class_name}}/{{shard_name}}"
    }
   ]
  },
  {
   "title": "Startup Disk I/O ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(startup_diskio_throughput_sum[$__interval])/rate(startup_diskio_throughput_count[$__interval])",
     "legendFormat": "{{operation}} ({{class_name}}/{{shard_name}})"
    }
   ]
  }
 ]
}